### PR TITLE
Default the PSK, username, and password from the environment.

### PR DESCRIPTION
**Pull request by dsoprea**

### CODE REVIEW

**Comment by hwdsl2** [comment]
First, thank you for your contribution.

I think it is best to keep those variables inside the script (which is the way it is now), instead of depending on external variables to be set. I am closing this but you are welcome to update your copy of forked repo with those changes.

**Comment by dsoprea** [comment]
Behavior stays the same. If they're not set, then the values stay empty.

On the other hand, my use case has the following constraints:

1. Need to explicitly set the public and private IPs because I have multiple *interfaces and I need to use the IP on the second interface. Since I'm running a network-in-a-network, I need to also use a public IP that can't be detected. So, I need to update these values directly in the scripts.

2. Need to set simple password and shared-secret because I'm currently using this to test some stuff in multiple environments and it's not ideal and potentially error-prone punching in long, randomized values. So, I need to set these values directly into the file.

Since I'm testing in multiple environments, this also equates to a lot of hand-editing every time I clone the repository.

It's a backwards-compatible change and doesn't require awareness of the feature unless it's actually needed, in which case it's very convenient. Otherwise it forces people to not be able to use the tool as designed thereby reducing it to being no more useful than a *gist*. I'd encourage you to merge it. I'd also really appreciate it if you choose to.

**Comment by hwdsl2** [comment]
@dsoprea Thank you for the detailed response. Yes I think your idea has its merits. But there is a subtle issue regarding the original single quotes around VPN variables. They must be replaced with double quotes for this to work. Give me a bit more time to think about this.

Would you mind opening a new PR based on the current master? I pushed a few documentation changes after you forked the repo. Or if you prefer, I can make the changes myself without you opening a new PR. Just let me know.

**Comment by dsoprea** [comment]
Ah. Yes. Is that because of the potential use of your script as EC2
user-data?

**Comment by dsoprea** [comment]
See #23.

**Pull request closed without merging**
