### PR TITLE
Update vpnsetup.sh

### PR DESCRIPTION
**Pull request by ppatrickxctw**
fix line 318 "+mschap-v2" to "require-mschap-v2" for windows support

### CODE REVIEW

**Comment by hwdsl2** [comment]
@ppatrickxctw Thank you for contributing! In my earlier tests "+mschap-v2" does work for Windows VPN clients. Could you share more context (or your configuration) on why this change is required?

**Comment by ppatrickxctw** [comment]
@hwdsl2 Because my Windows VPN client doesn't work on this, until I found this on the bottom libreswan's wiki page.
https://libreswan.org/wiki/VPN_server_for_remote_clients_using_IKEv1_with_L2TP

And your /etc/ppp.options.server would contain:
```
ipcp-accept-local
ipcp-accept-remote
refuse-eap
require-mschap-v2
noccp
noauth
idle 1800
mtu 1200
mru 1200
defaultroute
noipdefault
usepeerdns
debug
lock
connect-delay 5000
name YourName
password YourPassword
```

After I change "+mschap-v2" to "require-mschap-v2", it works.

**Comment by hwdsl2** [comment]
@ppatrickxctw What is your Windows version (e.g. Windows 10 2004)? Are you using the native IPsec/L2TP VPN client in Windows? Please share these additional details.

**Review by obaikhld1 — APPROVED** [review]

**Comment by hwdsl2** [comment]
@ppatrickxctw Please provide more information (requested in comment above) so I can try to reproduce the issue. Currently, the `+mschap-v2" in file "/etc/ppp/options.xl2tpd" would allow both CHAP and MSCHAP-v2. Tested with xl2tpd in Debian 10.

If we change it to "require-mschap-v2", it would only accept MSCHAP-v2, and break compatibility with users who selected CHAP but not MSCHAP-v2 in their Windows VPN settings.

**Comment by hwdsl2** [comment]
@ppatrickxctw Closing due to lack of response, please feel free to reply if you have more information.

**Pull request closed without merging**
