### PR TITLE
simplify coding and improve key pair creation process

### PR DESCRIPTION
**Pull request by Scottpedia**

### CODE REVIEW

**Comment by Scottpedia** [comment]
Please do not merge this PR yet. I am gonna update the AWS template docs in this PR too, with guidance on cleaning up the unused key pairs. Thanks!
@hwdsl2

**Comment by Scottpedia** [comment]
***New Task Note:***
- The template used to create a key pair every time a stack is created. That is due to the limitation that newly-created stacks don't have a way to know any existing key pairs that were previously created by the template. So there is no reusability in that sense.
- The way key pairs are created creates "Garbage key pairs", ones left over by their deleted parent stacks. Though the maximum number of key pairs allowed in an AWS region is 5000, holding a bunch of useless key pairs at a time can be annoying.
- We have considered letting user choose one of his/her own existing key pairs to be used by the template. However, the text field of template creation wizard does not support automatically listing of existing key pairs, which increases the chance of error due to typo of key pair names.

### Solution 

The upcoming version of the template will make sure that the user only holds one key pair at all time, which is created by the first ever stack deployment of this template, and then used by all subsequent stacks. Later stack deployments identify that particular key pair by looking at the tags of all existing key pairs. The key pair to be used by this template will have a tag like the following:
```json
{
    "Key": "created-by",
    "Value": "setup-ipsec-vpn"
}
```

The key material of that key pair is shown in the `Output` section of the first stack created from this template. In that case, users should be either notified to save the key material at that occasion, or acknowledged of where to find it later on.(the output text of a stack is preserved even after it is deleted.)

This change involves modifying the embedded python script within the template used to create new key pairs, and the output section of the stack deployment. And related documents should be updated in response too.

This note acts as a checklist and a summary of what the upcoming commits are about. Please help me to review this solution. Thanks! @hwdsl2 

[csr]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/walkthrough-crossstackref.html

**Comment by hwdsl2** [comment]
@Scottpedia Thanks for thinking about ideas on improving the template. There are some potential issues with re-using the key pair for later Cloudformation stack deployments. After a stack is deleted, the "output" section is no longer available to the user because they cannot "view" the stack after deletion. You can test this yourself by deleting a stack, then refresh the Cloudformation console, after which you will be unable to view the stack information.

To avoid this issue, we can perhaps continue using the existing solution, which I think is good enough for most use cases, and just add a note in the README on how to clean up the key pairs manually if needed.

**Comment by Scottpedia** [comment]
I actually think we can view the output of the deleted stacks, just by selecting "deleted" in the sorting option above the stack list. I will try it out later to see if it actually works...

**Comment by Scottpedia** [comment]
Screen Shot 2021-01-05 at 02 43 35

As you can see here.

**Comment by Scottpedia** [comment]
I just decided that I would not add this feature in this PR, but maybe in the future. That is because I would expect some users to experience even more severe inconvenience while tracing back the first stack(which would be probably deleted), and extract the key material from the output... 

Instead, I will work on updating the docs with guidance on cleaning up the left-over key pairs.

**Comment by Scottpedia** [comment]
I did some research for how to clean of the key pairs of deleted stacks. Since AWS does not warn users when they try to delete a key pair that is still use, and there is no way to determine if one is still in use on the portal, I don't think there is a proper way for users to "clean up" these key pairs.

However, I think we can update the template such that no key pairs on ec2 exist at all after deployment. And it does not affect users' access to instances using these keys.(since the key material is always available) At the same time, we might want to add the instance id to the stack output so that users can navigate to the instance associated with the key pair used more easily.

Please let me know your ideas on this solution. @hwdsl2

**Comment by hwdsl2** [comment]
@Scottpedia It could be as simple as adding a one-line note to README, like "After you delete a Cloudformation stack deployed using this template, the key pair that was added during deployment won't be automatically cleaned up. To manage your key pairs, go to EC2 console -> Key Pairs."

Regarding your idea on "no key pairs on EC2 exist after deployment", I think it may have some issues. Currently, the `ec2.create_key_pair` method is used in the template to generate keys. An alternative solution to that might have security concerns when generating the key pair. As I said earlier, the key pair cleanup is not a major issue, and the current solution is likely good enough for most users.

**Pull request closed without merging**
