### PR TITLE
Remove "Beta" banner on AWS page, and possibly a few minor improvements.

### PR DESCRIPTION
**Pull request by Scottpedia**
In the forked repo, I removed the Beta banner for both English and Chinese README.md. 

Before merging this forked repo, I have a few more improvement proposals to make. First, can we add a suffix to the template's filename?(i.e. from `cloudformation-template` to `cloudformation-template.json`) That is for better machine readability of the file when being edited. 

Also can we use a python dictionary to store the EC2 AMIs in the customized template script instead of using conditioning? That is for potentially more images to be added in the future.

### CODE REVIEW

**Comment by hwdsl2** [comment]
@Scottpedia Thanks for contributing! You can remove the "Beta" wording from the title too. The improvements you mentioned sounds good, either in this PR or in a separate PR.

**Comment by Scottpedia** [comment]
I've made the changes, please take a look when you are free. Thanks!

**Comment by Scottpedia** [comment]
If convenient, could you please give me a feedback of my work by checking the "insights" tab on the repo's page? I understand github does not show the download numbers of the template file, but you should be able to see the page view number of `/aws` page from "insights", if I am correct. Thanks again!

**Comment by hwdsl2** [comment]
@Scottpedia I'm happy to provide feedback on your work, but the "insights" tab unfortunately only shows the top 10 visited pages in this repo. I checked and the `/aws` page is not one of them as of now. The current list shows:
```
Repo home page
clients.md
README-zh.md
clients-zh.md
ikev2-howto.md
Issues
ikev2-howto-zh.md
clients-xauth.md
clients-xauth-zh.md
Search
```

**Comment by Scottpedia** [comment]
Oh I see. Because I did not see many issues regarding the AWS template, I wonder if people actually used it. Maybe it is working fine without issue then... So nevermind :P

**Comment by hwdsl2** [comment]
@Scottpedia By the way, I have one minor suggestion for the "EC2PrivateKeyMaterial" output under the "outputs" tab. Currently, the private key output is on a single line, and users must manually replace spaces with newlines before using the key.

If you have time, perhaps you can look into how to format the output for this variable better so that the key can be used directly after copy-pasting into a file.

**Comment by Scottpedia** [comment]
> @Scottpedia By the way, I have one minor suggestion for the "EC2PrivateKeyMaterial" output under the "outputs" tab. Currently, the private key output is on a single line, and users must manually replace spaces with newlines before using the key.
> 
> If you have time, perhaps you can look into how to format the output for this variable better so that the key can be used directly after copy-pasting into a file.

@hwdsl2 Hi 
I experimented with the cloudformation template to see if I can get the newline to work. But it did not work out. And now I can be pretty sure the output tab does not allow newline. I tried all different possible representations of newlines, and none of them was recognized by the cf portal.

**Pull request merged**
