### PR TITLE
Update cloudformation-template-ipsec

### PR DESCRIPTION
**Pull request by Scottpedia**
Hi @hwdsl2 , I saw your edits to the template file last night. And I want to point out the reason I chose to use `'debian-stretch-hvm-x86_64-gp2-*'` instead of the exact AMI Name of the Debian image is that the script in that scope sorts out all the images whose names follow that pattern in the order of the release date and choose the latest one to use. That way, we don't need to maintain this template when newer releases come out in the future.

### CODE REVIEW

**Comment by Scottpedia** [comment]
```python
#The following code block sorts out the latest relaese of a certain kind of image.
response = ec2.describe_images(Filters=[{'Name':'name', 'Values':[IAMName]}])
images = response['Images']
images.sort(key=creation_date,reverse=True)
AMIId = images[0]['ImageId']
```

**Comment by hwdsl2** [comment]
Thank you for the update. The script you mentioned does not check which AWS account owns the images, and because anyone can publicly share an AMI with arbitrary name, there's a risk that a non-official image is returned there. Changing the name to be more specific could help to avoid that scenario, which is the reason I made the changes.

For example, for Debian 10 there's explicit mention of which AWS account owns the images here:
https://wiki.debian.org/Cloud/AmazonEC2Image/Buster

If we can add a check to filter images based on AWS account ID, then changing it to a wildcard might be OK.

**Comment by hwdsl2** [comment]
@Scottpedia Looks like the describe_images call can filter by AWS account ID (owner):
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.describe_images

AWS account ID for Ubuntu (Canonical) is 099720109477, for Debian 10 it is 136693071363, and for Debian 9 it is 379101102735. I will make a change to the script to filter by these owners, change the image names back to using wildcards, and close this PR. Thanks!

**Comment by Scottpedia** [comment]
Thanks for the changing. Have a good sleep!

**Pull request closed without merging**
