### PR TITLE
Add link to cloudformation console to the cloudformation page for user convenience.

### PR DESCRIPTION
**Pull request by Scottpedia**
Please check the commits below.

### CODE REVIEW

**Comment by hwdsl2** [comment]
@Scottpedia Thank you for contributing! I suggest that you change those links to be the same as the "Launch stack" button:
https://console.aws.amazon.com/cloudformation/home#/stacks/new

**Comment by Scottpedia** [comment]
@hwdsl2  I have just changed the link, please take a look.

**Comment by hwdsl2** [comment]
@Scottpedia Can you update the link in README-zh.md too?

**Comment by Scottpedia** [comment]
Sorry I forgot that.

**Comment by hwdsl2** [comment]
@Scottpedia Thanks for updating. There's an extra parameter in your link in README-zh.md, can you remove the `?region=eu-central-1` part from the URL?

**Comment by Scottpedia** [comment]
@hwdsl2  Damn... Now I think it's all right. My bad....

**Pull request merged**
