### PR TITLE
Add Beta RHEL 8.0 support

### PR DESCRIPTION
**Pull request by lazerl0rd**
Had to build fail2ban due to missing server-optional repo and the move to python3.

### CODE REVIEW

**Comment by lazerl0rd** [comment]
Just fixed placement of some exit errors in that force-push.

**Comment by lazerl0rd** [comment]
If anyone wants to know why I'm using RHEL 8 it's due to systemd-resolved's support for DNSoTLS and DNSSEC for services I run, I suspect this may be a pull-factor for others too.

**Comment by letoams** [comment]
On Wed, 8 May 2019, Laster K. wrote:

> If anyone wants to know why I'm using RHEL 8 it's due to systemd-resolved's support for DNSoTLS and DNSSEC for
> services I run, I suspect this may be a pull-factor for others too.

Note that in the past (I don't know if this is still current),
systemd-resolved would send out DNS queries over _all_ its interfaces,
and believe the first reply (whether or not DNSSEC signed). This leads
to two security issues:

1) A closeby attacker (eg the wifi hotspot) can spoof answers that are
    normally dnssec protected
2) DNS queries meant to only be for the VPN internal networks are _also_
    send to public resolvers of other interfaces, leading to a privacy loss.

Again, I don't know the current state of systemd-resolved. I would
suggest you do some research before deploying that setup.

Paul

**Comment by lazerl0rd** [comment]
> On Wed, 8 May 2019, Laster K. wrote: If anyone wants to know why I'm using RHEL 8 it's due to systemd-resolved's support for DNSoTLS and DNSSEC for services I run, I suspect this may be a pull-factor for others too.
> Note that in the past (I don't know if this is still current), systemd-resolved would send out DNS queries over _all_ its interfaces, and believe the first reply (whether or not DNSSEC signed). This leads to two security issues: 1) A closeby attacker (eg the wifi hotspot) can spoof answers that are normally dnssec protected 2) DNS queries meant to only be for the VPN internal networks are _also_ send to public resolvers of other interfaces, leading to a privacy loss. Again, I don't know the current state of systemd-resolved. I would suggest you do some research before deploying that setup. Paul

Thanks, the server is a VPS over ethernet with basically just that. I have reason to believe that a close-by attacker cannot get close enough without me knowing ~an hour in advance at least due to the current situation.

Systemd-resolved seemed to have been changed quite a bit in the version I'm using on RHEL 8 Beta, but I'll check it up.

Anyways I prefer highly a DoT situation where my privacy with my resolver is safe over a local loss of privacy.

**Comment by hwdsl2** [comment]
@lazerl0rd First, thank you for contributing! I think now is not a good time to support RHEL 8 because the EPEL repository for RHEL 8 is not yet available. When it becomes available, perhaps we won't need to compile `fail2ban` from source. I'm closing this, but you are welcome to adapt this project to your needs, according to the license.

**Comment by lazerl0rd** [comment]
Thanks @hwdsl2, yeah compiling from source here is a bit iffy. ELRepo 8 is out so just waiting of Fedora to drop that EPEL 8 :).

**Pull request closed without merging**
