### PR TITLE
Updated readme with information about wifi routers

### PR DESCRIPTION
**Pull request by PositiveAlex**
Several models of routers could block ipsec/l2tp connections so those should be enabled explicitly in the router web interface.

Please point to my lexical errors. Thanks.

### CODE REVIEW

**Comment by PositiveAlex** [comment]
@hwdsl2 hi please add more reviewers

**Comment by hwdsl2** [comment]
@PositiveAlex Thank you for contributing.

In your changes you mentioned "remote management with IPSEC", which I don't understand. Maybe you were referring to the "IPsec VPN Passthrough" settings on routers [1]? Many routers, such as TP-Link, already have that setting ON by default.

[1] http://www.tp-link.com/us/FAQ-558.html

**Comment by PositiveAlex** [comment]
Hi, i wrote it as it written in my routers page

tew

**Comment by hwdsl2** [comment]
@PositiveAlex It looks like that the TRENDnet brand routers are special because that setting on the "remote management" page actually configures IPsec VPN passthrough. See [1].

In general, the option is called IPsec passthrough on most routers. See [2-4]. Many routers have it enabled by default.

[1] http://www.trendnet.com/emulators/TEW-651BR_V2.2R/help_manage.htm#Management_RemMan
[2] http://www.tp-link.com/us/FAQ-558.html
[3] https://kb.netgear.com/966/Troubleshooting-VPN-passthrough-for-home-routers
[4] http://www.linksys.com/us/support-article?articleNum=135452

**Comment by PositiveAlex** [comment]
Thanks, I will correct this info

**Pull request closed without merging**
