### PR TITLE
Pull default values from the environment

### PR DESCRIPTION
**Pull request by dsoprea**
I removed the quotes to get around the single/double-quote error. Let me know if this won't work.

### CODE REVIEW

**Comment by hwdsl2** [comment]
Looks good. Can you please:

1. Change the first line to 
   ```
   IPSEC_PSK=$IPSEC_PSK
   ```

2. Remove these two lines. You can still define `PUBLIC_IP` and `PRIVATE_IP` in the environment - it just does not have to be mentioned in the top section. I plan to add a note in the README.
   ```
   PUBLIC_IP=$VPN_PUBLIC_IP
   PRIVATE_IP=$VPN_PRIVATE_IP
   ```
   Thanks!

**Comment by hwdsl2** [comment]
Can you also modify `vpnsetup_centos.sh` with these changes? By the way, do you think it is a good idea to prefix everything with `VPN_`? e.g. `IPSEC_PSK` -> `VPN_IPSEC_PSK`, `PUBLIC_IP` -> `VPN_PUBLIC_IP`, `PRIVATE_IP` -> `VPN_PRIVATE_IP`. If that is better, feel free to replace all of them in the two scripts. Or I can do that myself after merging.

**Comment by dsoprea** [comment]
I tend to prefix the name of the tool to environment variables in order to avoid collisions. In this case, I figured that the whole name or even "VPNSETUP" might be unnecessarily long when a "VPN_" prefix was unlikely to have collisions, especially when considering that no VPN software is likely to exist at the time that this tool is run. I called it "VPN_IPSEC_PSK" and not "IPSEC_PSK" because it wasn't IPSEC that required it (it's consumed by this tool). I'll rename them to whatever you want because it's more of a preference and this is your tool and your call. Just consider the previous and let me know if you'd still like me to change anything. 

Of course, I'll still go ahead and update the CentOS script and move the IP-related ones, too, after I get this information.

**Comment by hwdsl2** [comment]
Thanks for the quick response. Yes can you please replace every occurence of the following variables in both `vpnsetup.sh` and `vpnsetup_centos.sh`:
```
IPSEC_PSK -> VPN_IPSEC_PSK
PUBLIC_IP -> VPN_PUBLIC_IP
PRIVATE_IP -> VPN_PRIVATE_IP
```

Also remove the two `PUBLIC_IP` and `PRIVATE_IP` lines in the top section.

**Comment by dsoprea** [comment]
Sure, but I'll have to do this tonight later.

**Comment by hwdsl2** [comment]
@dsoprea Please take your time, you can do this when you are convenient.

**Comment by hwdsl2** [comment]
@dsoprea Please see https://github.com/dsoprea/setup-ipsec-vpn/pull/1.

**Comment by hwdsl2** [comment]
Sounds good. For your convenience, here are the files with proposed changes. I haven't removed the two PRESET yet.   
https://github.com/hwdsl2/setup-ipsec-vpn/blob/develop/vpnsetup.sh   
https://github.com/hwdsl2/setup-ipsec-vpn/blob/develop/vpnsetup_centos.sh

**Comment by dsoprea** [comment]
I just submitted the PR. It has the agreed-upon changed. Merge at your
convenience.

**Comment by hwdsl2** [comment]
:+1: Thank you. I'll proceed to update the docs.

**Comment by dsoprea** [comment]
Thanks, Lin. This is a great tool and I greatly appreciate the amount of
work that went into it (the *iptables* rules always come to mind). Thank
you for your willingness to make some automation-friendly changes.

**Comment by hwdsl2** [comment]
You are welcome @dsoprea. And thank you for contributing.

**Pull request merged**
