### PR TITLE
Re-add AWS Deployment Template

### PR DESCRIPTION
**Pull request by scottpedia**
I am still doing testings, and will let you know when things are ready to be reviewed. @hwdsl2

### CODE REVIEW

**Comment by scottpedia** [comment]
TO-DO:

- [ ] Remove the cloudformation desinger metadata to keep the code clean.
- [ ] See if there are newer Debian distros with desktop kernels on AWS EC2.
- [ ] If the above fails, add note to the docs and post-deployment text that L2TP may not be available on Debian distros.
- [ ] Test if Ubuntu 22.04 now works with cfn notification script. (Reference: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1186)

**Comment by scottpedia** [comment]
Note: To install helper scripts on Debian 12 cloud images using `pip`, one has beforehand remove `/usr/lib/python3.*/EXTERNALLYMANAGED` so that system-wide resources can be modified.
Reference: https://peps.python.org/pep-0668/

**Comment by scottpedia** [comment]
@hwdsl2 I have done most of the editing, and please take a look while I finish the testing of VPN connections. All covered OS options have been tested for installation.

**Comment by scottpedia** [comment]
@hwdsl2 I have just done testing all OS options for their connection. All worked fine after some minor fixings, except the Debian machines are unable to use L2TP as expected.

**Comment by scottpedia** [comment]
TO-DO:
-[ ] Add support for CentOS Stream 8/9.

**Comment by hwdsl2** [comment]
@scottpedia Thank you for contributing! I'll make some minor edits after merging.

**Comment by scottpedia** [comment]
@hwdsl2 Hi Li
Thank you for checking out. I am wondering though if there is a way to let users obtain the ikev2 profiles after the deployment succeeds. One possible approach is to use an S3 bucket for downloading the profiles. Another solution is to set up a web server on the instance in a way that VPN profiles get served as downloadable content.

Which one do you think is preferable? Let me know your opinions.

**Comment by hwdsl2** [comment]
@scottpedia That is a good idea. Using an S3 bucket may be more preferred, as it may be more secure than the other option.

**Pull request merged**
