### PR TITLE
fix availability zone selection.

### PR DESCRIPTION
**Pull request by Scottpedia**
Different AWS users each possesses a different set of availability zones that s/he can use in a specific region. I used to select the zone ending with "a", until I found out some users in certain regions have zones starting from "b" or even "c". (e.g.`ca-central-1b`, `ca-central-1c`, and so on) This causes errors in cases where user does not have a `*a` zones. This PR fixes that issue by using AWS's intrinsic functions to query the available AZs during deployment.

### CODE REVIEW

**Comment by hwdsl2** [comment]
@Scottpedia Thanks for contributing! Looks good, but can you restore the newline at the end of the file, which was accidentally removed in this PR?

**Comment by Scottpedia** [comment]
sure but what's the purpose of that? Better machine readability? Help me understand.

**Comment by hwdsl2** [comment]
@Scottpedia It's not specific to JSON files. Generally, it is recommended to end POSIX text files with a newline. See these discussions for reference:
https://github.com/netlify/netlify-cms/issues/1382
https://github.com/serverless/serverless/issues/1321
https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

**Comment by Scottpedia** [comment]
> @Scottpedia It's not specific to JSON files. Generally, it is recommended to end POSIX text files with a newline. See these discussions for reference:
> https://github.com/netlify/netlify-cms/issues/1382
> https://github.com/serverless/serverless/issues/1321
> https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

Thank you for the clarification!

**Pull request merged**
